---
- hosts: localhost
  vars:
    path_pem: "{{ lookup('ini', 'path_pem section=local file=ansible.ini') }}" # path to your *.pem key enabling the creation of the cluster
    aws_key_name: "{{ lookup('ini', 'aws_key_name section=aws file=ansible.ini') }}" # name of your key in aws
  remote_user: root
  tasks:
    - name: Get Information Instances
      command: aws2 ec2 describe-instances --filters Name=key-name,Values="{{aws_key_name}}" Name=instance-state-name,Values=running
      register: output_dns

    - set_fact:
        output_json: "{{ output_dns.stdout | from_json }}"

    - set_fact:
        ec2_instances: "{{output_json.Reservations[0].Instances}}"

    - name: Docker stop
      command: |
        ssh -i "{{ path_pem }}" ubuntu@"{{item.PublicDnsName}}" 
        'sudo docker stop cassandra-gdelt'
      loop: "{{ ec2_instances }}"  

    - name: Instances stop 
      command: aws2 stop-instances --instance-ids "{{item.InstanceId}}"
      loop: "{{ ec2_instances }}"  
